# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", inline: <<-SHELL
    # Ensure Minikube is installed and start it
    if ! type minikube > /dev/null; then
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      sudo mv minikube /usr/local/bin/
    fi
    minikube start --driver=none

    # Explore Kubernetes architecture
    kubectl get nodes
    kubectl describe node
  SHELL
end
