# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", inline: <<-SHELL
    # Ensure Minikube and kubectl are installed and start Minikube
    if ! type minikube > /dev/null; then
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      chmod +x minikube
      sudo mv minikube /usr/local/bin/
    fi
    if ! type kubectl > /dev/null; then
      curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
    fi
    minikube start --driver=none

    # Enable metrics-server for monitoring
    minikube addons enable metrics-server
    # Apply a sample application for logging
    kubectl apply -f https://k8s.io/examples/debug/counter-pod.yaml
  SHELL
end
